"""init

Revision ID: 0001
Revises: 
Create Date: 2026-01-22 21:15:55.897583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create schema first
    op.execute('CREATE SCHEMA IF NOT EXISTS gepvi_reports')

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('sender_method', sa.String(), nullable=False),
    sa.Column('meta', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gepvi_reports'
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('next_task_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gepvi_reports'
    )
    op.create_index('idx_tasks_next_task_time', 'tasks', ['next_task_time'], unique=False, schema='gepvi_reports')
    op.create_index('idx_tasks_user_id', 'tasks', ['user_id'], unique=False, schema='gepvi_reports')
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['gepvi_reports.tasks.id']),
    sa.PrimaryKeyConstraint('id'),
    schema='gepvi_reports'
    )
    op.create_index('idx_reports_user_id', 'reports', ['user_id'], unique=False, schema='gepvi_reports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reports_user_id', table_name='reports', schema='gepvi_reports')
    op.drop_table('reports', schema='gepvi_reports')
    op.drop_index('idx_tasks_user_id', table_name='tasks', schema='gepvi_reports')
    op.drop_index('idx_tasks_next_task_time', table_name='tasks', schema='gepvi_reports')
    op.drop_table('tasks', schema='gepvi_reports')
    op.drop_table('notifications', schema='gepvi_reports')

    # Drop schema
    op.execute('DROP SCHEMA IF EXISTS gepvi_reports CASCADE')
    # ### end Alembic commands ###
