"""add notification fields

Revision ID: 0002
Revises: 0001
Create Date: 2026-01-29 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to notifications table
    op.add_column('notifications', sa.Column('status', sa.String(), nullable=False, server_default='new'), schema='gepvi_reports')
    op.add_column('notifications', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'), schema='gepvi_reports')
    op.add_column('notifications', sa.Column('report_id', sa.Integer(), nullable=True), schema='gepvi_reports')

    # Add foreign key constraint
    op.create_foreign_key('fk_notifications_report_id', 'notifications', 'reports', ['report_id'], ['id'], source_schema='gepvi_reports', referent_schema='gepvi_reports')

    # Add indexes
    op.create_index('idx_notifications_status_sender_method', 'notifications', ['status', 'sender_method'], unique=False, schema='gepvi_reports')
    op.create_index('idx_notifications_in_progress_updated_at', 'notifications', ['updated_at'], unique=False, schema='gepvi_reports', postgresql_where=sa.text("status = 'in_progress'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notifications_in_progress_updated_at', table_name='notifications', schema='gepvi_reports')
    op.drop_index('idx_notifications_status_sender_method', table_name='notifications', schema='gepvi_reports')
    op.drop_constraint('fk_notifications_report_id', 'notifications', schema='gepvi_reports', type_='foreignkey')
    op.drop_column('notifications', 'report_id', schema='gepvi_reports')
    op.drop_column('notifications', 'retry_count', schema='gepvi_reports')
    op.drop_column('notifications', 'status', schema='gepvi_reports')
    # ### end Alembic commands ###
