"""add timezone field to users

Revision ID: 0002
Revises: 0001
Create Date: 2026-01-04 18:14:58.117636

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='Europe/Moscow'), schema='gepvi_users')
    op.alter_column('webhooks', 'webhook_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               schema='gepvi_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhooks', 'webhook_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               schema='gepvi_users')
    op.drop_column('users', 'timezone', schema='gepvi_users')
    # ### end Alembic commands ###
