"""add user profile fields and weight history

Revision ID: 0003
Revises: 0002
Create Date: 2026-01-09 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add profile fields to users table
    op.add_column('users', sa.Column('yob', sa.Integer(), nullable=True), schema='gepvi_users')
    op.add_column('users', sa.Column('weight', sa.Numeric(precision=4, scale=1), nullable=True), schema='gepvi_users')
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True), schema='gepvi_users')
    op.add_column('users', sa.Column('height', sa.Integer(), nullable=True), schema='gepvi_users')
    op.add_column('users', sa.Column('activity_level', sa.Numeric(precision=3, scale=2), nullable=True), schema='gepvi_users')

    # Add CHECK constraint for gender (only 'm' or 'f')
    op.create_check_constraint(
        'ck_users_gender',
        'users',
        "gender IN ('m', 'f')",
        schema='gepvi_users'
    )

    # Create weight_history table
    op.create_table(
        'weight_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', postgresql.UUID(), nullable=False),
        sa.Column('weight', sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='gepvi_users'
    )

    # Create indexes for weight_history
    op.create_index('idx_weight_history_user_id', 'weight_history', ['user_id'], schema='gepvi_users')
    op.create_index('idx_weight_history_created_at', 'weight_history', ['created_at'], schema='gepvi_users')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop weight_history table and its indexes
    op.drop_index('idx_weight_history_created_at', table_name='weight_history', schema='gepvi_users')
    op.drop_index('idx_weight_history_user_id', table_name='weight_history', schema='gepvi_users')
    op.drop_table('weight_history', schema='gepvi_users')

    # Drop gender CHECK constraint
    op.drop_constraint('ck_users_gender', 'users', schema='gepvi_users')

    # Drop profile fields from users table
    op.drop_column('users', 'activity_level', schema='gepvi_users')
    op.drop_column('users', 'height', schema='gepvi_users')
    op.drop_column('users', 'gender', schema='gepvi_users')
    op.drop_column('users', 'weight', schema='gepvi_users')
    op.drop_column('users', 'yob', schema='gepvi_users')

    # ### end Alembic commands ###
